# Generated by Django 5.0.4 on 2025-08-19 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='firstapp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_country', models.CharField(max_length=64)),
                ('destnation_country', models.CharField(max_length=64)),
                ('number_of_night', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
